#!/usr/bin/env python3
"""Auto-generate tools/variants.json by picking 1-3-appearance cids
with the highest unique-color counts, prioritising those currently in
global groups (they're wasting global slots). Allocates new cid numbers
from the free DCOS pool [100, 174..198] (26 slots) and removes
variantified cids from cost_groups.json.

Strategy:
  - candidate cids: 1 <= drawn_in_count <= 3
  - priority: in_global > not_in_global, then unique-color count desc
  - variants_needed[cid] = drawn_in_count - (1 if home_rid in drawn_in else 0)
    (when home == one of the drawn rooms, keep the original cid for that
    room and only create variants for the others)
  - stop when DCOS budget exhausted

Outputs:
  tools/variants.json   — declarations consumed by apply_variants.py
  tools/cost_groups.json updated — removes variantified cids from groups
"""

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
from pristine_cache import cache  # noqa: E402
from decode_all import parse_index_room_names  # noqa: E402

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
VARIANTS_F = os.path.join(REPO_ROOT, 'tools', 'variants.json')
GROUPS_F   = os.path.join(REPO_ROOT, 'tools', 'cost_groups.json')
REFS_F     = os.path.join(REPO_ROOT, 'tools', 'costume_refs.json')

# Free DCOS slots in the pristine MI2 index. cid 0 is reserved (transparent).
FREE_CIDS = [100] + list(range(174, 199))


def main():
    refs = json.load(open(REFS_F))
    groups_cfg = json.load(open(GROUPS_F))
    names = parse_index_room_names()
    rid_to_name = names
    name_to_rid = {n: r for r, n in names.items()}

    cid_to_group = {}
    for g in groups_cfg['groups']:
        for cid in g['cids']:
            cid_to_group[cid] = g['name']

    # Build candidate list with priorities
    candidates = []
    for cid_s, rooms in refs['drawn_in'].items():
        if not rooms:
            continue
        cid = int(cid_s)
        n = len(rooms)
        if not (1 <= n <= 3):
            continue
        home = cache.cost_home(cid)
        if home is None:
            continue
        cs = next((c for c in cache.room(home)['costumes']
                   if c['cost_id'] == cid), None)
        if cs is None or not cs['frames']:
            continue
        n_pi = len(set(b for f in cs['frames'] for b in f['pixels'] if b != 0))
        home_in_drawn = home in rooms
        variants_needed = n - (1 if home_in_drawn else 0)
        if variants_needed == 0:
            # cid only appears in its home room → already per-room. skip.
            continue
        # Variant target rooms: every drawn room except home (if home is one
        # of them — that room keeps the original cid).
        target_rooms = sorted(r for r in rooms if r != home)
        candidates.append({
            'cid': cid,
            'n_pi': n_pi,
            'group': cid_to_group.get(cid),
            'home': home,
            'home_in_drawn': home_in_drawn,
            'target_rooms': target_rooms,
            'variants_needed': variants_needed,
        })

    # Sort: in-global first (priority lifting from starved global groups),
    # then by unique-color count descending.
    candidates.sort(key=lambda c: (
        0 if c['group'] else 1,
        -c['n_pi'],
    ))

    # Allocate
    picked = []
    cid_pool = list(FREE_CIDS)
    for c in candidates:
        if len(cid_pool) < c['variants_needed']:
            continue
        new_cids = [cid_pool.pop(0) for _ in range(c['variants_needed'])]
        for new_cid, target_rid in zip(new_cids, c['target_rooms']):
            picked.append({
                'new_cid': new_cid,
                'src_cid': c['cid'],
                'target_room': rid_to_name.get(target_rid, f'room{target_rid}'),
                '_note': f'cid {c["cid"]} clone ({c["n_pi"]} colours, '
                         f'group={c["group"] or "-"})',
            })

    # Write variants.json
    variants_doc = {
        '_comment': (
            'Auto-generated by tools/generate_variants.py. Each entry creates '
            'a NEW cid (allocated from the free DCOS pool [100, 174..198]) '
            'that is a per-room copy of an existing src_cid. The variant '
            'lives in target_room\'s LFLF, gets re-encoded against that '
            'room\'s joint --best palette (no global lock), and every '
            'Costume(src_cid) call inside target_room\'s scripts is rewritten '
            'to Costume(new_cid).'),
        'variants': picked,
    }
    with open(VARIANTS_F, 'w') as f:
        json.dump(variants_doc, f, indent=2)
        f.write('\n')

    # Update cost_groups.json: remove variantified cids from their groups
    # if and only if all their target rooms get variants AND home isn't a
    # drawn room (i.e. the original cid is orphan, no room uses it anymore).
    full_removal_cids = set()
    for c in candidates:
        # Did this cid get all its needed variants picked?
        picked_for_cid = sum(1 for p in picked if p['src_cid'] == c['cid'])
        if picked_for_cid == c['variants_needed'] and not c['home_in_drawn']:
            full_removal_cids.add(c['cid'])
    # If home IS in drawn, the original cid is still used in the home room —
    # keep it in the group so its home room gets the global lock.
    n_removed = 0
    for g in groups_cfg['groups']:
        before = list(g['cids'])
        g['cids'] = [c for c in g['cids'] if c not in full_removal_cids]
        if len(g['cids']) != len(before):
            removed = [c for c in before if c not in g['cids']]
            print(f"  group {g['name']}: removed cids {removed}")
            n_removed += len(removed)
    # Use targeted text rewrite to preserve formatting (same trick the
    # slot solver uses).
    text = open(GROUPS_F).read()
    for g in groups_cfg['groups']:
        new_arr = '[' + ', '.join(str(c) for c in g['cids']) + ']'
        pat = (r'("name":\s*"' + re.escape(g['name']) + r'".*?'
               r'"cids":\s*)\[[^\]]*\]')
        text, _ = re.subn(pat, r'\g<1>' + new_arr, text, count=1, flags=re.DOTALL)
    open(GROUPS_F, 'w').write(text)

    print(f'\nWrote {VARIANTS_F}: {len(picked)} variants')
    print(f'Updated {GROUPS_F}: removed {n_removed} cid(s) from groups')


if __name__ == '__main__':
    main()
